right_arm:
  r_shoulder_fan:
    fan:
      id: 10
  r_shoulder_pitch:
    dxl_motor:
      type: MX-106
      id: 10
      offset: 1.57
      direct: False
      cw_angle_limit: -3.14
      ccw_angle_limit: 1.05
  r_shoulder_roll:
    dxl_motor:
      type: MX-64
      id: 11
      offset: 1.57
      direct: False
      cw_angle_limit: -1.75
      ccw_angle_limit: 1.57
  r_arm_yaw:
    dxl_motor:
      type: MX-64
      id: 12
      direct: False
      cw_angle_limit: -1.57
      ccw_angle_limit: 1.57
  r_elbow_fan:
    fan:
      id: 13
  r_elbow_pitch:
    dxl_motor:
      type: MX-64
      id: 13
      direct: False
      cw_angle_limit: 0.0
      ccw_angle_limit: 2.18
  r_forearm_yaw:
    dxl_motor:
      type: AX-18
      id: 14
      direct: False
      cw_angle_limit: -1.75
      ccw_angle_limit: 1.75
  r_wrist_fan:
    fan:
      id: 15
  r_wrist_pitch:
    dxl_motor:
      type: MX-28
      id: 15
      direct: False
      cw_angle_limit: -0.79
      ccw_angle_limit: 0.79
  r_wrist_roll:
    dxl_motor:
      type: AX-18
      id: 16
      direct: False
      cw_angle_limit: -0.79
      ccw_angle_limit: 0.79
  _motor_a:
    type: XL-320
    id: 3
    direct: True
    cw_angle_limit: -2.15
    ccw_angle_limit: 2.44
  _motor_b:
    type: XL-320
    id: 5
    direct: True
    cw_angle_limit: -2.62
    ccw_angle_limit: 2.04
  _motor_lift:
    type: XL-320
    id: 7
    direct: True
    cw_angle_limit: -2.62
    ccw_angle_limit: 2.62
